### ISSUE TITLE
Typo in TransportBuilder.php

### ISSUE THREAD

**Issue by eranishojha** [elastic/elastic-transport-php#12]
https://github.com/elastic/elastic-transport-php/blob/main/src/TransportBuilder.php#L128

Should be `Cloud ID not valid`, instead of `Could ID not valid`.

**Comment by ezimuel** [comment]
Thanks @eranishojha, fixed in https://github.com/elastic/elastic-transport-php/commit/f4ed45936e4ae6e9f3c3e4ab30a2c976b5a841c9
