### ISSUE TITLE
写请求日志时获取body，导致发出请求时body为空

### ISSUE THREAD

**Issue by jooklove** [elastic/elastic-transport-php#16]
问题代码位置src/Transport.php  239行

**Comment by ezimuel** [comment]
I'm sorry @jooklove but I don't speak Chinese and in this repository we speak English. I used a [translator](https://www.deepl.com/translator) and the result is:
```
Problem code location src/Transport.php line 239
```
I don't understand the issue. Can you elaborate? You can use the mentioned translator for writing in English. Thanks.
