### ISSUE TITLE
Transport does not support user:pass in node connection url

### ISSUE THREAD

**Issue by rumman23** [elastic/elastic-transport-php#18]
Hi,
we use node uris with user and password (eg. https://user:pass@example.com). This information is not copied when requestUri is taken from node pool in [Transport::getConnectionUrl](https://github.com/elastic/elastic-transport-php/blob/main/src/Transport.php#L219).

Transport should call `$request->getUri()->withUserInfo()` when `$node->getUri()->getUserInfo` contains user and/or password.

**Comment by ezimuel** [comment]
@rumman23 sorry for the late reply, you can specify the username and password using `Transport::setUserInfo($user, $password)`. Anyway, you right we need to fix this in `Transport::setupConnectionUri()`. I'm working on a PR to support this.

**Comment by ezimuel** [comment]
@rumman23 this is the PR #22
