### ISSUE TITLE
Stack trace: SimpleNodePool.php on line 83

### ISSUE THREAD

**Issue by mdys** [elastic/elastic-transport-php#25]
`PHP 8.3.8 (cli) (built: Jun  4 2024 14:53:17) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.3.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.8, Copyright (c), by Zend Technologies`

`elasticsearch-8.11.0`

`Stack trace:
#0 /home/wwwroot/html_50001_download/vendor/elastic/transport/src/Transport.php(291): Elastic\Transport\NodePool\SimpleNodePool->nextNode()
#1 /home/wwwroot/html_50001_download/vendor/elasticsearch/elasticsearch/src/Client.php(168): Elastic\Transport\Transport->sendRequest()
#2 /home/wwwroot/html_50001_download/vendor/elasticsearch/elasticsearch/src/Traits/ClientEndpointsTrait.php(1899): Elastic\Elasticsearch\Client->sendRequest()
#3 /home/wwwroot/html_50001_download/controller/asr_down.php(306): Elastic\Elasticsearch\Client->update()
#4 /home/wwwroot/html_50001_download/vos_server_o.php(953): asr_down::do_down()
#5 [internal function]: vos_cdr->onTask()
#6 {main}
  thrown in /home/wwwroot/vendor/elastic/transport/src/NodePool/SimpleNodePool.php on line 83`

`$es_client = Elastic\Elasticsearch\ClientBuilder::create()->setHosts([$serv->es_client])->build();	     
			 
			$es_up_data_arr = [
			    'doc' => [
			    	'asr_reason' => [$asr_reason],
			      'asr_status' => [$asr_status],
			    	'asr_url' => $asr_url				        
			    ],
			];

			// 
			$es_up_data_params = [
			    'index' => 'asr_cdr_log_new',  
			    'id' => $server_flowno,
			    'body' => $es_up_data_arr,
			];

			$es_response = $es_client->update($es_up_data_params);`

**Comment by ezimuel** [comment]
@mdys can you report the error message that is generated? I don't see it in the stack trace.
Moreover, I noticed that you are using elasticsearch-php 8.11.0, did you try with the latest 8.14.0?
Thanks.

**Comment by mdys** [comment]
Yes ,I used  8.14.0.
But the same problem has arisen, and I am not sure if it is caused by the high concurrent load of elasticsearch-log or if there is a problem with my code design. Report the same error.

**Comment by ezimuel** [comment]
@mdys can you report the error message? Thanks.

**Comment by mdys** [comment]
> Stack trace: 
#0 /home/wwwroot/html_50001_download/vendor/elastic/transport/src/Transport.php(291): Elastic\Transport\NodePool\SimpleNodePool->nextNode() 
#1 /home/wwwroot/html_50001_download/vendor/elasticsearch/elasticsearch/src/Client.php(168): Elastic\Transport\Transport->sendRequest() 
#2 /home/wwwroot/html_50001_download/vendor/elasticsearch/elasticsearch/src/Traits/ClientEndpointsTrait.php(1899): Elastic\Elasticsearch\Client->sendRequest() 
#3 /home/wwwroot/html_50001_download/controller/asr_down.php(306): Elastic\Elasticsearch\Client->update() 
#4 /home/wwwroot/html_50001_download/vos_server_o.php(953): asr_down::do_down() 
#5 [internal function]: vos_cdr->onTask() 
#6 {main} thrown in /home/wwwroot/vendor/elastic/transport/src/NodePool/SimpleNodePool.php on line 83

**Comment by ezimuel** [comment]
@mdys I'm sorry but this is not the error message, this is the stack trace. I need to have the error message to understand the issue. Typically, the error message is something like `Fatal error: ...`.

**Comment by mdys** [comment]
Thank you, I have resolved this issue. I have added a retry mechanism and tried to execute it again without any errors

> for($retry_i=0;$retry_i<=4;$retry_i++){
 	  
	try {
		
		$es_client = Elastic\Elasticsearch\ClientBuilder::create()->setHosts([$serv->es_client])->setRetries(5)->build(); 
		$es_response = $es_client->bulk($es_up_data_params);
		
		$is_restry=0;
		
		break;
		
	}  catch (Error $e) { 
		pub_class::logger(json_encode($es_up_data_params),'es-cdr1');
		
	}
	sleep(0.2);
}
