### ISSUE TITLE
https://github.com/elastic/elasticsearch-php is gone

### ISSUE THREAD

**Issue by mbrodala** [elastic/elastic-transport-php#31]
Currently https://github.com/elastic/elasticsearch-php is gone and yields a 404:

![Image](https://github.com/user-attachments/assets/78e32e53-5ba1-4719-8039-8227b3285b8e)

As you can guess, this breaks basically anything, as e.g. Composer is unable to install this package (dist archives are also fetched via Github, Git clone fallback is pointless).

Since I don't know where else to report this, I've picked this repository. Please move/forward this if necessary.

**Comment by colons-litzmann** [comment]
Same here. I also picked a random PHP repo

**Comment by standa** [comment]
https://x.com/quentinpradet/status/1851233467604041824

> This is an automation error, this will be fixed shortly. Sorry for the inconvenience!

**Comment by mbrodala** [comment]
Thanks for the reply. Can you share the status on a sane platform, too? 🙏

**Comment by sidz** [comment]
Also https://discuss.elastic.co/t/was-the-elasticsearch-php-repository-deleted/369723/2

**Comment by mbrodala** [comment]
Seems like it was restored in the meantime.
