### ISSUE TITLE
Transport.php depends on having Composer; composer.json doesn't contain the dependency.

### ISSUE THREAD

**Issue by lkorczewski** [elastic/elastic-transport-php#8]
`Transport.php` has `use Composer\InstalledVersions;` But this dependency on having Composer is not stated in composer.json. You can't assume the application has source code of Composer in `vendor`.

I got the error while using Client::index() from elasticsearch/elasticseach.

**Comment by ezimuel** [comment]
@lkorczewski the `Composer\InstalledVersions` class is always present in `vendor/composer` when you use `composer` to install dependencies. Are you using `elastic/elasticsearch-php` without composer?

**Comment by ezimuel** [comment]
@lkorczewski I [discovered](https://getcomposer.org/doc/07-runtime.md#installed-versions) that there is a virtual package named `composer-runtime-api` manageg by composer that I can put as requirement, even if the `Composer\InstalledVersions` is always installed when using composer.
Can you try to add this requirement in composer.json and let me know if this solve the issue? Thanks!
```json
    "require" : {
        // ...
        "composer-runtime-api": "^2.0"
    },
```

**Comment by ezimuel** [comment]
@lkorczewski I sent this PR https://github.com/elastic/elastic-transport-php/pull/10 for fixing the issue. Let me know if this solve your issue, thanks!

**Comment by ezimuel** [comment]
Solved in https://github.com/elastic/elastic-transport-php/pull/10
